Rename ubuntu package from murmur back to mumble-server
git-svn-id: https://mumble.svn.sourceforge.net/svnroot/mumble/trunk@916 05730e5d-ab1b-0410-a4ac-84af385074fa

diff --git a/debian/mumble-server.postrm b/debian/mumble-server.postrm
--- a/debian/mumble-server.postrm
+++ b/debian/mumble-server.postrm
@@ -21,15 +21,15 @@ set -e
 
 case "$1" in
     purge)
-    	[ -f /var/log/murmur/murmur.log ] && rm -f /var/log/murmur/murmur.log
-    	[ -f /var/lib/murmur/murmur.sqlite ] && rm -f /var/lib/murmur/murmur.sqlite
-    	[ -f /var/run/murmur/murmur.pid ] && rm -f /var/run/murmur/murmur.pid
-    	[ -d /var/run/murmur ] && rmdir --ignore-fail-on-non-empty /var/run/murmur
+    	[ -f /var/log/mumble-server/mumble-server.log ] && rm -f /var/log/mumble-server/mumble-server.log*
+    	[ -f /var/lib/mumble-server/mumble-server.sqlite ] && rm -f /var/lib/mumble-server/mumble-server.sqlite
+    	[ -f /var/run/mumble-server/mumble-server.pid ] && rm -f /var/run/mumble-server/mumble-server.pid
+    	[ -d /var/run/mumble-server ] && rmdir --ignore-fail-on-non-empty /var/run/mumble-server
 	if [ -x "$(command -v deluser)" ]; then
-		deluser --quiet --system murmur > /dev/null || true
-		deluser --quiet --system --group --only-if-empty murmur > /dev/null || true
+		deluser --quiet --system mumble-server > /dev/null || true
+		deluser --quiet --system --group --only-if-empty mumble-server > /dev/null || true
 	else
-		echo >&2 "not removing 'murmur' system account because deluser command was not found"
+		echo >&2 "not removing 'mumble-server' system account because deluser command was not found"
 	fi    	
     ;;
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
