More Ubuntu updates
git-svn-id: https://mumble.svn.sourceforge.net/svnroot/mumble/trunk@851 05730e5d-ab1b-0410-a4ac-84af385074fa

diff --git a/debian/murmur.postrm b/debian/murmur.postrm
--- a/debian/murmur.postrm
+++ b/debian/murmur.postrm
@@ -24,11 +24,12 @@ case "$1" in
     	[ -f /var/log/murmur/murmur.log ] && rm -f /var/log/murmur/murmur.log
     	[ -f /var/lib/murmur/murmur.sqlite ] && rm -f /var/lib/murmur/murmur.sqlite
     	[ -f /var/run/murmur/murmur.pid ] && rm -f /var/run/murmur/murmur.pid
+    	[ -d /var/run/murmur ] && rm -f --ignore-fail-on-non-empty /var/run/murmur
 	if [ -x "$(command -v deluser)" ]; then
 		deluser --quiet --system Murmur > /dev/null || true
 		deluser --quiet --system --group --only-if-empty Murmur > /dev/null || true
 	else
-		echo >&2 "not removing $USERNAME system account because deluser command was not found"
+		echo >&2 "not removing Murmur system account because deluser command was not found"
 	fi    	
     ;;
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
@@ -46,5 +47,3 @@ esac
 #DEBHELPER#
 
 exit 0
-
-
